{
 "title": "monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES  WITH KEY = \"host\""
   },
   {
    "name": "disk",
    "query": "SHOW TAG VALUES FROM \"check_diskspace_usage\"  WITH KEY = \"unique_name\"  WHERE (\"host\" =~ /^$hostname$/)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "check_total_cpu_usage",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "check_total_memory_usage",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "check_total_cpu_usage",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-0" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-1" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-2" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-3" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-4" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-5" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-6" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-7" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-8" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-9" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-10" }
     ]
    },
    {
     "measurement": "check_cpu_usage_per_core",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=", "value": "check_cpu_usage_per_core-11" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature in °C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "check_cpu_temp",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "check_total_memory_usage",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Procs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "check_procs",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "check_diskspace_usage",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "unique_name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Updates APT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "check_updates_apt",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Updates yay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "check_updates_yay",
     "select": [
      [
       { "params": [ "out_float" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}